### ISSUE TITLE
Error after Update PVE

### ISSUE THREAD

**Issue by n3roGit** [takala-jp/zabbix-proxmox#32]
After Updaing to the latest "7.1-10" i got the following errors.

```
root@zabbix:/opt# /opt/proxmox_cluster.py -a ck6.fritz.box -u zabbix@pve -p 'PASSWORD' -t Proxmox_Cluster
Traceback (most recent call last):
  File "/opt/proxmox_cluster.py", line 200, in <module>
    node_status = proxmox.nodes(n).status.get()
  File "/usr/local/lib/python3.8/dist-packages/proxmoxer/core.py", line 105, in get
    return self(args)._request("GET", params=params)
  File "/usr/local/lib/python3.8/dist-packages/proxmoxer/core.py", line 90, in _request
    raise ResourceException("{0} {1}: {2} - {3}".format(
proxmoxer.core.ResourceException: 596 Errors during TLS negotiation, request sending and header processing: Connection timed out - b''
```

**Comment by takala-jp** [comment]
Hi there, the script is compatible with Proxmox 7.  It would appear that the key part of that error is: `Connection timed out`

Closing as connectivity issue.
